### ISSUE TITLE
Check the `invitations` field from the Profile GraphQl query

### ISSUE THREAD

**Issue by amiskov** [cambiatus/backend#110]
Go to https://staging.cambiatus.io/api/graphiql and try to run this query:

```graphql
{
  profile(input: {account: "lucca"}) {
    invitations
  }
}
```
Get the [500 error](https://sentry.io/share/issue/1693d590c97f4559bc4fff8c7aa98943/). This [must be a `cast` problem](https://cambiatus.slack.com/archives/CA83HJAAD/p1605035510498600?thread_ts=1605034853.498000&cid=CA83HJAAD).

**Comment by lucca65** [comment]
fixed on #111
