### ISSUE TITLE
Investigate memory errors on production

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#130]
Due to some errors in production, happening during database operations, we have to update our dependencies and OTP, the logs from the errors are very obfuscated so lets try to just update everything as a first try before diving deeper into what's causing this.

**Comment by venomnert** [comment]
Hey Lucca would you be able to give me access to production logs? Because I would like to start updating 1 deps at the time rather than updating the whole thing all at once.

**Comment by lucca65** [comment]
sure, I'll send it over slack

**Comment by venomnert** [comment]
- [ ] Become comfortable with staging env first
- [ ] Get access to prod server
- [ ] Review prod logs to get a better understanding of issue
- [ ] Provide findings
