### ISSUE TITLE
Support phone numbers for more countries

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#144]
Support phone numbers from the following countries:
- [x] Portugal  - `351 xx xxx xxxx`
- [x] Canada - `1 xxx xxx xxxx`
- [x] UK - `44 20 xxxx xxxx`
- [x] NZ - `64 2xxx xxxx(xx)`

**Comment by venomnert** [comment]
Portugal number format `+351 xx xxx xxxx`

**Comment by venomnert** [comment]
Hey @heltonlr I tested the backend and its looks like the library recognizes Portugal number. You just need to pass the country code `+351`

**Comment by lucca65** [comment]
@venomnert if the backend is ok, the redirect must be to @NeoVier, @heltonlr do the final UX/UI testing, he don't interact with the backend, only through the frontend

**Comment by venomnert** [comment]
@lucca65 sorry about the confusion. I have fixed my comment.

**Comment by lucca65** [comment]
@venomnert reopening this to address more phone numbers
