### ISSUE TITLE
Add rich link preview to the shop

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#182]
**Is your feature request related to a problem? Please describe.**
When users share Cambiatus links it is shown plain, without a preview

**Describe the solution you'd like**
Implement a preview with the product image and the community logo. Maybe with some text like "${user} is selling ${product} on Cambiatus, check it out"

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Screen shots**
<img width="547" alt="Captura de Tela 2021-05-12 às 12 39 48" src="https://user-images.githubusercontent.com/1082127/118003650-25889c00-b31f-11eb-988f-667c36e340fc.png">

**Comment by juramos-2020** [comment]
Olá pessoal!
tudo bem?

vocês já tem tudo o que precisam de Design para essa implementação? Vocês vão precisar das telas?

**Comment by lucca65** [comment]
Ju acho que essa funcionalidade não tem nenhuma tela. você tinha pensado em alguma coisa?

**Comment by juramos-2020** [comment]
Tinha pensado em [algo assim](https://www.figma.com/file/OSqvmNO3HSzRJSrp9Of865/New-Shop?node-id=1672%3A6427), mas tranquilo se já fizeram 😉👍

Se precisarem de alguma ajuda para as telas de compartilhamento de perfis é só falar 😉👍

**Comment by lucca65** [comment]
Ju não tenho permissão pra ver esse link

**Comment by juramos-2020** [comment]
Ops, tranquilo. 

Acabei de mandar um convite para vocês e expliquei ainda pouco no Slack ([aqui nessa conversa](https://cambiatus.slack.com/archives/CA83HJAAD/p1654518428323399)) sobre a migração de projetos que estamos fazendo no Figma. 😉👍

**Comment by lucca65** [comment]
Ju tem um elemento que não colocamos na loja, de ter o preço depois da descrição. @MatheusBuss pode criar uma issue pra colocarmos isso?

**Comment by MatheusBuss** [comment]
Acho que isso é algo que vamos tratar na #239. Lá já tem alguma descrição do que pensamos em fazer. É legal já pensar em como vão ficar as imagens sim 👍.

**Comment by lucca65** [comment]
não vamos tratar da imagem? pq aqui acho que é mais colocar o preço após a descrição do produto mesmo

**Comment by MatheusBuss** [comment]
> Ju tem um elemento que não colocamos na loja, de ter o preço depois da descrição. @MatheusBuss pode criar uma issue pra colocarmos isso?

Podemos fazer isso sim, só teria que ver se o preço não precisaria vir antes da descrição, por que se for no final pode ficar cortado.

**Comment by lucca65** [comment]
> Podemos fazer isso sim, só teria que ver se o preço não precisaria vir antes da descrição, por que se for no final pode ficar cortado.

@juramos-2020 oq acha? Realmente é bem comum os celulares cortarem por falta de espaço

**Comment by juramos-2020** [comment]
Poderia ter uma quebra de linha?
No máximo duas linhas que nem [nessa proposta](https://www.figma.com/file/OSqvmNO3HSzRJSrp9Of865/New-Shop?node-id=1672%3A6427). Será que funciona?

**Comment by lucca65** [comment]
Não dá Ju, infelizmente só podemos ter uma linha que é gerenciada pelo app que for mostrar (Instagram, zap, etc) 

Uma outra ideia seria colocar o preço na frente da **descrição**, acho que inclusive podemos colocá-la em negrito, certo @MatheusBuss?

**Comment by MatheusBuss** [comment]
Imaginava que funcionaria bem o negrito, mas pelo jeito nem sempre. O negrito pode fucionar, mas depende mais da plataforma que vai mostrar a preview pro usuário. Pelo menos é o que falaram [nessa thread](https://stackoverflow.com/questions/19888327/can-i-bold-description-meta-tag). Podemos dar uma testada nisso.

**Comment by lucca65** [comment]
entendi obrigado pela pesquisa @MatheusBuss! O que acha @juramos-2020? Com ou sem negrito, a proposta seria colocar o preço antes da descrição

**Comment by juramos-2020** [comment]
Tudo bem sim se o preço vir antes. Também fica interessante nesse formato 😉👍
