### ISSUE TITLE
Render markdown on transfer email

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#184]
After https://github.com/cambiatus/frontend/issues/615, we now allow for rich text on transfers memo. Rendering might be off when sending emails, so we must make sure we are properly rendering it. We use pure markdown, so it might be easy with libs like https://github.com/pragdave/earmark

**Comment by ryguigas0** [comment]
Hey could you assign me this and add the hacktoberfest tag?

**Comment by lucca65** [comment]
Doen @ryguigas0 good luck!

**Comment by ryguigas0** [comment]
Hey is there an list of routes I can use for sending transfer emails?

**Comment by lucca65** [comment]
hey @ryguigas0 there is no need for you to worry about routes. In this app in particular no routes trigger emails.

Instead you can run this command on the project:

```sh
$ iex -S mix phx.server
```

This will start an interactive console for the project, where you can call email sending directly!

```elixir
iex(1)> Repo.all(Cambiatus.Commune.Transfer) |> hd |> CambiatusWeb.Email.transfer
```

Open your browser on `http://localhost:4000/dev/mailbox`. You should have enough to keep going

**Comment by ryguigas0** [comment]
That's all I needed to know thanks!

**Comment by ryguigas0** [comment]
Hello again! I've been trying anything I could to create an Transfer since Repo.all returned an empty list and seeds.exs doesnt have an Transfer created. Could explain me what are the Transfer struct and how its created and sent?

**Comment by lucca65** [comment]
hey @ryguigas0, maybe some knowledge with elixir would be useful! Here are some resources:

- https://www.youtube.com/watch?v=YQxopjai0CU
- https://hexdocs.pm/ecto/getting-started.html#inserting-data
- https://elixirschool.com/en/lessons/ecto/basics

I can grab a snippet but I think its worth the challenge for you! let me know if you need me to provide you the answer

**Comment by lucca65** [comment]
done! Yeah, please do! 💪

**Comment by ryguigas0** [comment]
Oops by project I meant the repo, also heres the [link](https://discord.com/channels/720788516837261322/735506115810426971/899784988839514173) you should also post something there, it might bring more contributors here
