### ISSUE TITLE
Send monthly emails with a digest of the news

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#195]
# Story

I, as an user of the community
Want to keep in touch with what's happening
To be more active and aware about the community

### Use cases

Given that the community has news enabled and had at least one news in the last 30 days
When it comes the end of each month
Then the system sends a digest with all news on the month

Given that the user has the preference of not receiving digest emails
When it comes the end of each month
Then the system dont send this user anything

### Problem description

After the Implementation of our news Broadcast on #188, we need to keep improving it by adding email digests

**Comment by lucca65** [comment]
@juramos-2020 @rafachadud @heltonlr Can you folks help us with the design for the digest? It will only contain headlines and can have multiple news inside of it, all of them will link back to the frontend

**Comment by juramos-2020** [comment]
Ok Lucca I will work on it 🤙

**Comment by juramos-2020** [comment]
OI @lucca65 

aqui está a proposta. Qualquer dúvida ou sugestão pode me marcar no figma 😉👍

https://www.figma.com/file/De9z2EjpGRkfsEXVzfj9u2/Support-News-%26-Digest-E-mails?node-id=738%3A7143
