### ISSUE TITLE
Move away from IPFS

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#23]
**Is your feature request related to a problem? Please describe.**
It is very frustrating to use images in the platform. Images take a while to load, sometimes they don’t appear even if the request of saving it worked.

**Make sure to migrate shop images in MUDA**

**Describe the solution you'd like**
Just use S3 

**Describe alternatives you've considered**
none

**Comment by RodrigoLeiteF** [comment]
Fixes cambiatus/frontend#130
