### ISSUE TITLE
Adicionar preço do produto no título da rich link preview

### ISSUE THREAD

**Issue by MatheusBuss** [cambiatus/backend#245]
Atualizar a funcionalidade do rich link preview para mostrar o preço dos produtos no título da preview

- [ ] Colocar o preço na descrição, antes de começar o texto, e em negrito
- [ ] Mostrar nome do autor

[Link do Figma](https://www.figma.com/file/OSqvmNO3HSzRJSrp9Of865/New-Shop?node-id=1672%3A6427)

![image](https://user-images.githubusercontent.com/102705968/172162811-2df63add-83f8-44be-afbd-f18935252436.png)

**Comment by lucca65** [comment]
Obrigado @MatheusBuss!
