### ISSUE TITLE
Adicionar rich_link_preview para categorias

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#253]
Com a introdução de categorias #237, adicionamos diversos campos utilizados por SEO e pelos pré-visualizadores de conteúdo. Devemos adicionar também no backend essa capacidade.

**Comment by NeoVier** [comment]
Devemos levar em conta que o meta title e meta description são opcionais. No caso de não estarem presentes, usamos o nome e descrição normais (que são obrigatórias).

Para a imagem, no preview que mostramos no frontend damos preferência ao `icon`. Se não estiver presente, mostramos o `image`
