### ISSUE TITLE
Create sharable invite links

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#26]
**Is your feature request related to a problem? Please describe.**
Users have been requesting for a while now a way to invite people to their community. Although we do have a way of doing that it requires you to fill in an email. Maybe it is best for us to create just a sharable link that allow users to register. It will be easier to share via WhatsApp and other messengers apps, and it can still work with email.

**Comment by natillasol** [comment]
Approximately, when will this feature be ready? I ask in order to get organized with the Organicoins community, because part of their actions is to invite people to the system and this feature is needed.

**Comment by natillasol** [comment]
Approximately, when will this feature be ready? I ask in order to get organized with the Organicoins community, because part of their actions is to invite people to the system and this feature is needed.

**Comment by lucca65** [comment]
Not sure yet @natillasol we didn't knew it was a priority until you asked on that issue, I'll make sure I'll add it to our next sprint

**Comment by natillasol** [comment]
Great! Next sprint being when?

**Comment by lucca65** [comment]
monday. But please don't promise any dates to our customers. We have other stuff to fix and only two devs. We still have to talk about it, plan what are the steps to make it work, give it an estimation, compare to other stuff we have to do, prioritise them and then do it. During the sprint we may also get a critical bug report so please don't use this date as something we can promise or agree with customers.
