### ISSUE TITLE
Corrigir tradução do email de digest em espanhol

### ISSUE THREAD

**Issue by MatheusBuss** [cambiatus/backend#267]
Uma seção do email de digest não está sendo traduzido para o espanhol. A imagem abaixo mostra que a parte central do email é enviada em inglês.

![image](https://user-images.githubusercontent.com/102705968/182147155-f294463b-a90e-422d-bc34-9a5b3eed7b77.png)

Isso ocorre porque não há uma tradução disponível na linha 85 do arquivo `priv/gettext/es-ES/LC_MESSAGES/default.po`. A linha 85 deve conter uma tradução da mensagem que está na linha 84.

**Comment by lucca65** [comment]
good catch! ⚾
