### ISSUE TITLE
Adicionar nome da comunidade no assunto de Digest

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#280]

**Comment by MatheusBuss** [comment]
@lucca65, @NeoVier, @juramos-2020 quais dessas opções ficaria melhor como assunto?

1. Mizu 水 - Notícias da comunidade
2. Notícias da comunidade - Mizu 水
3. Veja as últimas novidades de Mizu 水
4. Resumo das notícias de Mizu 水

Se tiverem uma sugestão de um assunto melhor, por favor me digam.

**Comment by juramos-2020** [comment]
> Notícias da comunidade Mizu 水

> Veja as últimas novidades de Mizu 水

Gostei dessas duas 😊

**Comment by NeoVier** [comment]
Gostei da número 2

**Comment by lucca65** [comment]
Gostei da 1, pois assim consigo ver a comunidade sem precisar abrir o e-mail, mesmo no mobile!
