### ISSUE TITLE
Update email info

### ISSUE THREAD

**Issue by MatheusBuss** [cambiatus/backend#284]
While developing #275 we noticed that there are some things in our emails that should be updated.

TO DO:
- [x] Update the footer to always represent the current year
- [x] Remove "former BeSpiral" from the footer
- [x] Update font on claim email

**Comment by MatheusBuss** [comment]
@juramos-2020 tem alguma coisa simples que achas que precisa ser atualizada nos nossos emails? Por enquanto só temos essas duas mudanças

**Comment by juramos-2020** [comment]
@mateus esse e-mail é aquele que recebemos quando a gente faz uma transferência?

Eu fiz uma transferência agora, na comunidade Muda para ver se eu recebia esse e-mail mas não recebi.

Eu só tenho o design no Figma mas não lembro se a implementação dele foi igual ao design. 

vc tem um print de como tá esse email hoje para eu dar uma olhadinha? 🙏

**Comment by MatheusBuss** [comment]
@juramos-2020 na Muda não vai funcionar mesmo, por enquanto só está funcionando em ambiente de staging mesmo. Se quiser testar por lá é pra funncionar. De qualquer jeito eu envio uns prints por aqui.

Transferência:
![image](https://user-images.githubusercontent.com/102705968/185267569-ecd5d2e3-7d5d-4bdc-bd3a-84f666a3234b.png)

Notícia (separei em duas porque era mas fácil pra mim 😅):
![image](https://user-images.githubusercontent.com/102705968/185267839-c7639a6a-0a77-42ed-a6b9-cecbaf319263.png)
![image](https://user-images.githubusercontent.com/102705968/185267899-7ce7a0a7-0c01-4194-8c50-8a78c2ba25fe.png)

Claim:
![image](https://user-images.githubusercontent.com/102705968/185268055-81968d86-004c-4311-888f-5a2c4cc78e92.png)

**Comment by MatheusBuss** [comment]
Olhando assim também percebi que a fonte do email de claim está diferente. Ele usa Tahoma ao invés de Nunito, mais uma coisa fácil de arrumar.

**Comment by juramos-2020** [comment]
Muito obrigada @MatheusBuss 🙏

Seria fácil também deixar o footer igual em todos os emails? Vi que também tem diferença entre eles. Podíamos usar como padrão o footer dos comunidade pois parece mais completo. O que vc acha?

**Comment by MatheusBuss** [comment]
Bem tranquilo copiar o footer sim @juramos-2020, podemos fazer nessa issue mesmo.

Mais duas sugestões que talvez podem ficar pra depois, dependendo de quando vamos fazer a próxima release e do que achas das sugestões.

1. Retirar a linha  do Github e colocar só o ícone ali do lado do LinkedIn, Instagram, etc.

2. Vendo o email do meu celular eu percebi que os ícones ficam difíceis de ver no modo escuro. Podemos pensar em um jeito de melhorar isso.

![Screenshot_20220817-223351_Gmail.jpg](https://user-images.githubusercontent.com/102705968/185273360-dc77c0a8-8ea5-4a7f-91a2-f80d5695d155.jpg)

**Comment by juramos-2020** [comment]
Arrasou @MatheusBuss super concordo com as suas sugestões ☺️

**Comment by juramos-2020** [comment]
Ah uma dúvida, esse link do subscribe tá direcionando para onde?

**Comment by MatheusBuss** [comment]
Ainda falta fazermos esse direcionamento certinho pro unsubscribe. Mas ele não vai ser responsabilidade do frontend com o resto do site. Estamos terminando a #275, daí ficará disponível no ambiente de staging.

**Comment by juramos-2020** [comment]
Ah tá combinado.

Não sei como tá andando isso mas acho que vai ser implementado uma opção de configurações no perfil do usuário. Aonde ele vai poder decidir quais notificações ele quer ativar:

https://www.figma.com/file/CO9QI0RyRxdx9ShfHJCo2g/Acessibilidade?node-id=1307%3A24327


Como esse e-mail é relacionado ao WebApp acho que podemos linkar essa página de configurações quando ela tiver pronta. O que vc acha? Dessa forma também direcionamos o usuário para voltar ao app e definir sua preferência de notificação.

Acho que o @NeoVier estava trabalhando nessa página, não tenho certeza.

**Comment by lucca65** [comment]
pessoal, teremos as duas páginas. Um pra quem estiver logado e outra pra ser usada pelo e-mail

**Comment by NeoVier** [comment]
@juramos-2020 não daria muito certo linkar para essa página no email, pois queremos que os usuários não precisem fazer login no app pra alterar essas preferências (imagina se alguém perdeu as 12 palavras, não consegue mais entrar no app e fica recebendo emails).

**Comment by juramos-2020** [comment]
> @juramos-2020 não daria muito certo linkar para essa página no email, pois queremos que os usuários não precisem fazer login no app pra alterar essas preferências (imagina se alguém perdeu as 12 palavras, não consegue mais entrar no app e fica recebendo emails).

Ah tá entendi. Faz todo sentido ☺️

**Comment by muguika** [comment]
Fantastic catch... So old details!
