### ISSUE TITLE
Misleading instructions in README

### ISSUE THREAD

**Issue by amiskov** [cambiatus/backend#36]
I cloned the project and followed the instructions from "[Building and running the application locally](https://github.com/cambiatus/backend#building-and-running-the-application-locally)" section in Readme. I failed because this instructions are outdated. Then I found [.github/setup.md](https://github.com/cambiatus/backend/blob/master/.github/setup.md) and run the project successfully.

**How it can be improved**
The section with outdated instructions could be replaced with the link to the right ones. Something like this:

```
## Building and running the application locally
Follow [these steps](.github/setup.md) to run the project on your computer.
```

**Comment by venomnert** [comment]
This issue has been resolved. We are now referring the [.github/setup.md](https://github.com/cambiatus/backend/blob/master/.github/setup.md) within our [readme](https://github.com/cambiatus/backend#development-environment-setup)
