### ISSUE TITLE
Add mutation for creating new users 25

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#57]
We currently have a Rest API for sign_up new users.  We'll need to create a new mutation to be used on the new sign_up process. That process will need to have the same functionality we have today (Invitation support and blockchain's netlink call) and also will need to have support for all the information related to KYC -- if the community enables it -- validate it and store it on our servers

Please be aware that Costa Rica has 3 different types of physical person and 3 different types of companies, we will need to find out the data format and validate everything

**Comment by amiskov** [comment]
> Please be aware that Costa Rica has 3 different types of physical person and 3 different types of companies

@lucca65 @RodrigoLeiteF can you, please, share the 3 company types? I found only Gran Empresa in the mockups...

**Comment by lucca65** [comment]
@heltonlr help us!

**Comment by heltonlr** [comment]
Sure, right now

**Comment by heltonlr** [comment]
So, there are two options in dropdown:

**MIPYME** and **Gran Empresa**

When the user choose MIPYME, the input below shows **MIPYME Number**

When the user choose **Gran Empresa**, the input below shows **Corporación Number**

But....I going to check this with Karla.

**Comment by amiskov** [comment]
Thank you, @heltonlr!

**Comment by lucca65** [comment]
Thanks @heltonlr you rock!

**Comment by heltonlr** [comment]
You are welcome @lucca65 @amiskov
