### ISSUE TITLE
Allow users to delete their KYC information 6

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#58]
We need to add a mutation to delete KYC information from the user profile

**Comment by amiskov** [comment]
This mutation should delete information from the DB for Natural persons and Companies as well. Tables in the DB involved in this deletion:

- `kyc_data` — empty the row with the given `account_id`;
- `addresses` — empty the row with the given `account_id`.

We have a separate task for implementing this on the frontend cambiatus/frontend/issues/315.
