### ISSUE TITLE
Add mutation to allow for existing users to update or fill in their KYC informations 25

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#60]
Users will need to be able to fill in their KYC information at any time, we need to provide a GraphQL mutation for that

We must just make sure we have the right mutation depending on which if its a `company` or `person`

**Comment by amiskov** [comment]
> Users will need to be able to fill in their KYC information at any time

I think this looks controversial for now.

We had a meeting about the Edit Profile page and we decided that _KYC information should not be editable_. The short resume of this conversation is available in [the description of this issue](https://github.com/cambiatus/frontend/issues/310#issue-666496720).

Also, we agreed that the only way for the user to fill the KYC information is either via the Registration process (new users) or via the Invitation process (existing users). And both Registration and Invitation process should be initialized with the invitation link to the community with KYC enabled.

So, my point here is that we need this mutation but we shouldn't allow users to edit theirs KYC info at any time.
 
@lucca65 are you agree with me?

**Comment by lucca65** [comment]
I guess the problem come from the wording `fill in their data`. Users should be able to add their KYC data anytime, as long as they belong to a community that needs it.

It doesn't mean we should allow them to edit, but rather, add or fill their data.

I think your interpretation is correct, just want to make clear that users should still be able to add their KYC. 

It also open up a case where users could delete and re-add their KYC, but I think the flag `is_verified` should be used in those cases -- of course, in the future when we add manual verification of that data.
