### ISSUE TITLE
Add account creation validations

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#66]
Add sign up validation for the account creation process, now we don't make any validations for the input values.

**Comment by RodrigoLeiteF** [comment]
We currently have the following validations:

1) `/@/` for email
2) `^[a-z1-5]{12}$` for account

Another candidate for validation would be the public key, but unfortunately I couldn't find any information on the format for EOS public keys. All I could gather was that *most* of them start with `EOS` and have length of 53. The `bespiral` key seems to be an exception, having 51 characters of length. Any ideas or resources I can look at?
