### ISSUE TITLE
Claim analysis history query is missing some results

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#71]
Some users are not being able to see some existing pending claims on their claim analysis history page (`/dashboard/analysis`)

That page uses [this function](https://github.com/cambiatus/backend/blob/a66b4d2a83a210cda7d9ed18b995dcf9c97675a4/lib/cambiatus/commune/commune.ex#L239-L271) to process the request. It is a composable query that allows the user to add status and claimer filters.

One of the reasons it don't work is because of [this line](https://github.com/cambiatus/backend/blob/a66b4d2a83a210cda7d9ed18b995dcf9c97675a4/lib/cambiatus/commune/commune.ex#L260):

```elixir
 where: fragment("?.validator_id = ? OR ?.claim_id IS NULL", ch, ^account, ch),
```

It makes sure to find only claims whose checks haven't been voted by the logged user yet. This is not the best way to do it. The best way is to add this SQL query instead:

```sql
select count(*) from checks where claim_id = claims.id and checks.validator_id = 'USER ACCOUNT HERE'
```

or in Ecto query:

```elixir
|> where(
      [c, a, o, v],
      o.community_id == ^community_id and v.validator_id == ^account and c.status == "pending" and
        fragment(
          "select count(*) from checks b where b.claim_id = ?.id and b.validator_id = ?",
          c,
          ^account
        ) == 0
    )
```

The problem is to add those filters only depending on what the user choose. Today we simply [add the status to the query](https://github.com/cambiatus/backend/blob/a66b4d2a83a210cda7d9ed18b995dcf9c97675a4/lib/cambiatus/commune/commune.ex#L265-L267):

```elixir
  def claim_filter_status(query, status) do
    query |> where(status: ^status)
  end
```

This function should be smarter to know that if its pending and not voted, the status should be different.

**Comment by lucca65** [comment]
@amiskov can you help me remember if we tackled this one? I remember we did, but I'm not sure this issue is from before or after we fixing that query

**Comment by amiskov** [comment]
@lucca65 Yep, we [did that](https://github.com/cambiatus/backend/pull/103/files/d01df8d33d11360ed8941ee13b0fdd837453066c#r513411589)!
