### ISSUE TITLE
Sign up mutation doesn't return an error when account already exists

### ISSUE THREAD

**Issue by RodrigoLeiteF** [cambiatus/backend#72]
Instead it returns a 500 Internal Server Error, leaving the frontend with no information on how to handle it.

**Comment by RodrigoLeiteF** [comment]
Likely related to this comment: https://github.com/cambiatus/backend/pull/69#pullrequestreview-477964185

**Comment by lucca65** [comment]
Yeah, the backend does know the account already exists, and it errors out. That is correct. Today the frontend [already checks for the existing account ](https://github.com/cambiatus/frontend/blob/cc47c0eb58e10f4f9fe8663ff748d8cff220de3b/src/index.js#L223). I'm not sure if we even need to fix it. At least not anytime soon

**Comment by lucca65** [comment]
now it does, actually for a while now
