### ISSUE TITLE
Images are uploaded without Content-Type

### ISSUE THREAD

**Issue by RodrigoLeiteF** [cambiatus/backend#73]
This can potentially cause issues on browser who don't try and interpret images regardless of Content-Type (maily Safari). We should detect the appropriate type from the file's extension and upload the file appropriately.

**Comment by lucca65** [comment]
The old implementation had mime type verification. I don't know if it was removed, but should be pretty straight forward to fix this.

**Comment by RodrigoLeiteF** [comment]
> The old implementation had mime type verification. I don't know if it was removed, but should be pretty straight forward to fix this.

Verifying the mime type isn't the problem. When the files are uploaded to S3, currently we don't send it's mime type as metadata. We need to patch that :)
