### ISSUE TITLE
Constraint error when using "upsertKyc" mutation

### ISSUE THREAD

**Issue by RodrigoLeiteF** [cambiatus/backend#82]
Error:
> constraint error when attempting to insert struct:    * kyc_data_account_id_fkey (foreign_key_constraint)If you would like to stop this constraint violation from raising anexception and instead add it as an error to your changeset, pleasecall `foreign_key_constraint/3` on your changeset with the constraint`:name` as an option.The changeset has not defined any constraint.

Query:
> {"query":"mutation {\n  upsertKyc2069213328: upsertKyc(input: {accountId: \"rodrigoky14\", countryId: \"1\", document: \"1231231231\", documentType: \"nite\", phone: \"11948340013\", userType: \"natural\"}) {\n    __typename0: __typename\n  }\n}"}

**Comment by amiskov** [comment]
This query works for me in the current `master` branch:

```graphql
mutation {
  upsertKyc(input: {accountId: "andreymiskov", countryId: "1", document: "1231231231", documentType: "nite", phone: "11948340013", userType: "natural"}) {
    phone
    country {
      name
    }
  }
}
```

I only changed `accountId` here. Is there any chance that we are using different versions of the backend? Maybe the issue is related to [changing `:string` to `:id`](https://github.com/cambiatus/backend/pull/80#issuecomment-692209332) for address fields?

**Comment by RodrigoLeiteF** [comment]
I did some more research and this seems to happen when trying to submit an address for a user that doesn't yet exist. We shouldn't ever hit this path, but it would be cool to have a proper error message nonetheless :)

**Comment by lucca65** [comment]
@victorgdev can you help us on this one?
