### ISSUE TITLE
Remove `isVerified` from the Upsert KYC mutation

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#83]
We currently allow for users to specify if their KYC is verified or not. This should be an internal process, must be removed for now

**Comment by amiskov** [comment]
> We currently allow for users to specify if their KYC is verified or not. 

`isVerified` field is used in a query, not in the mutation. We can't specify `isVerified` value in [`input_object` for updating KYC](https://github.com/cambiatus/backend/blob/master/lib/cambiatus_web/schema/kyc_types.ex#L66), we can only have it in the [returned data](https://github.com/cambiatus/backend/blob/master/lib/cambiatus_web/schema/kyc_types.ex#L55) after the mutation.

We can delete `isVerified` from the `:kyc_data` object, but I think `isVerified` could be useful on the frontend for implementing some restrictions for unverified users.

@lucca65 please, let me know if I'm mistaken somewhere!

**Comment by lucca65** [comment]
oh I see, thanks for the clarification @amiskov, the existing behaviour is the correct one
