### ISSUE TITLE
Add GraphQL instructions

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#93]
Add to README.md:

- Sample queries
- URL

**Comment by amiskov** [comment]
Also, it's worth to mention the `yarn generate-graphql` command (see `package.json`):

- what is the purpose of this command;
- from which package it comes from;
- how it's related to the backend.

**Comment by victorgdev** [comment]
This issue was closed on this [PR](https://github.com/cambiatus/backend/pull/105)
